version: '3.8'
services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-lite
    env_file:
      - .env
    volumes:
      - ./settings.yaml:/app/settings.yaml
    ports:
      - "0.0.0.0:7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - USE_LANGCHAIN=true
